apiVersion: apps/v1 
kind: Deployment
metadata:
  name: flask
  labels: 
     app: flask-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask

  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: "623479528468.dkr.ecr.us-east-1.amazonaws.com/flask:f87f944"
        ports:
        - containerPort: 80