---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.deployment.name }}-ingress"
  annotations:
    cert-manager.io/cluster-issuer: "acme-issuer-{{ .Values.deployment.env }}"

spec:
  ingressClassName: nginx
  rules:
    {{ if eq .Values.deployment.env "prod" }}
    - host: "{{ .Values.deployment.domain }}"
    {{- else }}
    - host: "{{ .Values.deployment.env }}.{{ .Values.deployment.domain }}"
    {{ end }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: "{{ .Values.deployment.name }}-svc"
              port:
                number: {{ .Values.service.port }}
  tls:
  - hosts:
      {{- if eq .Values.deployment.env "prod" }}
      - "{{ .Values.deployment.domain }}"
      {{ else }}
      - "{{ .Values.deployment.env }}.{{ .Values.deployment.domain }}"
      {{ end }}
    secretName: myingress-cert
