apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.deployment.name }}-svc"
spec:
  selector:
    app: {{ .Values.deployment.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
