---
    name: CI Pipeline
    
    on:
        push:
            branches:
              - '*'
 #             - '!main'
    
    jobs:
  
        build:
      
          name: Build Image
          runs-on: ubuntu-latest
     
          steps:
          # Check out the code
          - name: Check out code
            uses: actions/checkout@v4
            
          # Configure AWS credentials for authentication
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ env.AWS_REGION }}

          # Login to Amazon ECR (Elastic Container Registry)
          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v2
  
          - name: Get short SHA
            run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          # Build, tag, and push Docker image to Amazon ECR
          - name: Build, tag, and push image to Amazon ECR
            env:
              ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
              ECR_REPOSITORY: ${{ env.APP_NAME }}
              IMAGE_TAG: ${{ env.SHORT_SHA }}
            run: |
              docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
              docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
              echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
              echo "image_tag=$IMAGE_TAG" 
              echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"