name: "Terraform Infrastructure Change Management Pipeline"

on:
    push:
      branches:
      - terraform
      paths:
      - terraform/**
    pull_request:
      branches:
      - terraform
      paths:
      - terraform/**

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}            
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: terraform